### PR TITLE
Django 1.9 doc files in epub and mobi format

### PR DESCRIPTION
**Pull request by 5car1z**
Is this what you had in mind in regards to issue #6

### CODE REVIEW

**Comment by HashCode55** [comment]
This is actually not a stable release. Documentation for stable release is not available for download.

**Comment by 5car1z** [comment]
He just asked for the "Django 1.9 documentation". This is from https://docs.djangoproject.com/en/1.9/ - nothing was said about whether stability mattered or not.

**Comment by HashCode55** [comment]
I thing its kind of natural to assume that we want to provide the users with a stable release documentation.

**Comment by 5car1z** [comment]
If you can find it then do provide. I'm just supplying what was asked for (or the closest to).

**Comment by HashCode55** [comment]
Ah sorry, you did it fine... I thought you had pushed a pre release one.

**Comment by pferretti** [comment]
It's fine, this documentation was asked by @arpit1997. I know that it's for an old release, but for someone it could be useful.

**Pull request merged**
